trigger:
  - main

pool:
  name: "SelfHostedAgents"  # Use the correct pool name

steps:
# Step 1: Checkout the repository
- checkout: self  # Explicit checkout step

# Step 2: Create an artifact with the new name
- script: |
    echo "Hello World!" > coditas_artifact.txt
    mkdir -p $(Build.ArtifactStagingDirectory)
    mv coditas_artifact.txt $(Build.ArtifactStagingDirectory)/
  displayName: 'Create Artifact'

# Step 3: Publish the artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'my-artifact'
    publishLocation: 'Container'

# Step 4: Download the artifact (Ensures it's available on the agent)
- task: DownloadBuildArtifacts@0
  displayName: 'Download Artifact'
  inputs:
    artifactName: 'my-artifact'
    downloadPath: '$(Build.ArtifactStagingDirectory)'

# Step 5: Upload Artifact to SFTP Server
- script: |
    sshpass -p "admin" sftp -o StrictHostKeyChecking=no sftpuser@20.235.147.224
    cd /sftpuser/
    put $(Build.ArtifactStagingDirectory)/coditas_artifact.txt
    exit
    EOF
  displayName: 'Upload Artifact to SFTP Server'

# Step 6: SSH into SFTP Server and Transfer Artifact to Another Server
- script: |
    sshpass -p "coditas@12345" ssh -tt -o StrictHostKeyChecking=no coditas@20.235.147.224 <<EOF
    echo "Successfully logged into the SFTP server!"
    cd /sftp/sftpuser/
    ls -l
    sshpass -p "coditas@1234" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null /sftp/sftpuser/coditas_artifact.txt coditas@52.172.96.181:/home/coditas/
    exit
    EOF
  displayName: 'SSH into SFTP Server and Transfer Artifact'

