trigger:
  - main
pool:
  name: "SelfHostedAgents"  # Use the correct pool name
steps:
# Step 1: Checkout the repository
- checkout: self  # Explicit checkout step
# Step 2: Create an artifact
- script: |
    echo "Hello World!" > artifact.txt
    mkdir -p $(Build.ArtifactStagingDirectory)
    mv artifact.txt $(Build.ArtifactStagingDirectory)/
  displayName: 'Create Artifact'
# Step 3: Publish the artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'my-artifact'
    publishLocation: 'Container'
# Step 4: Download the artifact (Ensures it's available on the agent)
- task: DownloadBuildArtifacts@0
  displayName: 'Download Artifact'
  inputs:
    artifactName: 'my-artifact'
    downloadPath: '$(Build.ArtifactStagingDirectory)'
# Step 5: Copy artifact to SFTP server
- script: |
    sshpass -p "$(SFTP_PASSWORD)" scp -o StrictHostKeyChecking=no \
      $(Build.ArtifactStagingDirectory)/artifact.txt sftpuser@$(SFTP_SERVER_IP):uploads/artifact.txt

  displayName: 'Copy to SFTP Server'
  env:
    SFTP_PASSWORD: $(sftp_password)
    SFTP_SERVER_IP: $(sftp_server_ip)
    
trigger:
  - main

pool:
  name: "SelfHostedAgents"  # Ensure the correct agent pool is used



# Step 2: Download the Secure File (Private Key)
- task: DownloadSecureFile@1
  name: sshKey
  inputs:
    secureFile: 'sftpserver_key.pem'

# Step 3: Set Correct Permissions for the Private Key
- script: |
    chmod 600 $(sshKey.secureFilePath)
  displayName: 'Setup SSH Private Key'

# Step 4: Transfer Artifact to Target Server (52.172.96.181)
- script: |
    ssh -i $(sshKey.secureFilePath) azureuser@$(SFTP_SERVER_IP) << EOF
      scp /sftp/uploads/artifact.txt coditas@52.172.96.181:/home/coditas/
    EOF
  displayName: 'Transfer Artifact to Target Server'
  env:
    SFTP_SERVER_IP: $(sftp_server_ip)  # Ensure this variable is set in pipeline variables


