trigger:
  - main

pool:
  name: "SelfHostedAgents"  # Use the correct pool name

steps:
# Step 1: Checkout the repository
- checkout: self  # Explicit checkout step

# Step 2: Create an artifact
- script: |
    echo "Hello World!" > artifact.txt
    mkdir -p $(Build.ArtifactStagingDirectory)
    mv artifact.txt $(Build.ArtifactStagingDirectory)/
  displayName: 'Create Artifact'

# Step 3: Publish the artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'my-artifact'
    publishLocation: 'Container'

# Step 4: Download the artifact
- task: DownloadBuildArtifacts@0
  displayName: 'Download Artifact'
  inputs:
    artifactName: 'my-artifact'
    downloadPath: '$(Build.ArtifactStagingDirectory)'

# Step 5: Copy artifact to SFTP server (Fixed: Use `sftp` instead of `scp`)
- script: |
    sftp -o StrictHostKeyChecking=no sftpuser@$(SFTP_SERVER_IP) <<EOF
    cd uploads
    put $(Build.ArtifactStagingDirectory)/my-artifact/artifact.txt
    bye
    EOF
  displayName: 'Copy to SFTP Server'
  env:
    SFTP_SERVER_IP: $(sftp_server_ip)

# Step 6: Download SSH Private Key from Secure Files
- task: DownloadSecureFile@1
  name: downloadSFTPKey
  displayName: "Download SFTP Private Key"
  inputs:
    secureFile: "sftpserver_key.pem"

# Step 7: SSH into SFTP server and copy artifact.txt to another server (Fixed SSH part)
- script: |
    chmod 400 $(Agent.TempDirectory)/sftpserver_key.pem
    ssh -i $(Agent.TempDirectory)/sftpserver_key.pem -o StrictHostKeyChecking=no azureuser@$(SFTP_SERVER_IP) <<EOF
      cd /sftp/uploads
      ls -lah  # Verify file exists
      sftp -o StrictHostKeyChecking=no coditas@52.172.96.181 <<EOC
      put artifact.txt /home/coditas/
      bye
      EOC
    EOF
  displayName: "SSH into SFTP Server and Copy File to Another Server"






