trigger:
  - main

pool:
  name: "SelfHostedAgents"  # Use the correct pool name

steps:
# Step 1: Checkout the repository
- checkout: self  # Explicit checkout step

# Step 2: Create an artifact
- script: |
    echo "Hello World!" > artifact.txt
    mkdir -p $(Build.ArtifactStagingDirectory)
    mv artifact.txt $(Build.ArtifactStagingDirectory)/
  displayName: 'Create Artifact'

# Step 3: Publish the artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'my-artifact'
    publishLocation: 'Container'

# Step 4: Download the artifact (Ensures it's available on the agent)
- task: DownloadBuildArtifacts@0
  displayName: 'Download Artifact'
  inputs:
    artifactName: 'my-artifact'
    downloadPath: '$(Build.ArtifactStagingDirectory)'

# Step 5: Copy artifact to SFTP server
- script: |
    sshpass -p "$(SFTP_PASSWORD)" scp -o StrictHostKeyChecking=no \
      $(Build.ArtifactStagingDirectory)/artifact.txt sftpuser@$(SFTP_SERVER_IP):uploads/artifact.txt
  displayName: 'Copy to SFTP Server'
  env:
    SFTP_PASSWORD: $(sftp_password)
    SFTP_SERVER_IP: $(sftp_server_ip)

# Step 6: Download SSH Private Key from Secure Files
- task: DownloadSecureFile@1
  name: downloadSFTPKey
  displayName: "Download SFTP Private Key"
  inputs:
    secureFile: "sftpserver_key.pem"

# Step 7: SSH into the server using the private key
- script: |
    chmod 400 $(Agent.TempDirectory)/sftpserver_key.pem
    ssh -i $(Agent.TempDirectory)/sftpserver_key.pem -o StrictHostKeyChecking=no azureuser@13.71.109.194 "pwd; ls -lah"
  displayName: "SSH into SFTP Server and Check Directory"
