trigger:
  - main
pool:
  name: "SelfHostedAgents"  # Use the correct pool name

steps:
- task: DownloadSecureFile@1
  name: downloadSFTPKey
  displayName: "Download SFTP Private Key"
  inputs:
    secureFile: "sftpserver_key.pem"

- script: |
    chmod 600 $(Agent.TempDirectory)/sftpserver_key.pem
    echo "StrictHostKeyChecking no" >> ~/.ssh/config
  displayName: "Set up SSH Key"

- script: |
    ssh -i $(Agent.TempDirectory)/sftpserver_key.pem azureuser@13.71.109.194 "echo 'Connected to SFTP Server!'"
  displayName: "Test SSH Connection to SFTP Server"

- script: |
    if [ ! -f "/sftp/uploads/file.txt" ]; then
      echo "Error: File '/sftp/uploads/file.txt' not found!" && exit 1
    fi
  displayName: "Check if File Exists"

- script: |
    sudo apt-get update && sudo apt-get install -y sshpass
    export SSHPASS="$(CODITAS_DEPLOY_PASS)"
    sshpass -e scp /sftp/uploads/file.txt coditas@deploymachine:/home/coditas
  displayName: "Transfer File to Deploy Machine"
  env:
    CODITAS_DEPLOY_PASS: $(CODITAS_DEPLOY_PASS)
