trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self  # Explicit checkout step
  fetchDepth: 1   # Optional

- script: |
    echo "Hello World!" > artifact.txt
  displayName: 'Create Artifact'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: 'artifact.txt'
    ArtifactName: 'my-artifact'
    publishLocation: 'Container'

- script: |
    sshpass -p "$(SFTP_PASSWORD)" scp -o StrictHostKeyChecking=no \
      $(Pipeline.Workspace)/my-artifact/artifact.txt sftpuser@$(SFTP_SERVER_IP):/home/sftpuser/
  displayName: 'Copy to SFTP Server'
  env:
    SFTP_PASSWORD: $(sftp_password)
    SFTP_SERVER_IP: $(sftp_server_ip)
