trigger:
  - main

pool:
  name: "SelfHostedAgents"  # Use the correct pool name

steps:
- checkout: self  # Explicit checkout step

- script: |
    echo "Hello World!" > artifact.txt
    mkdir -p $(Build.ArtifactStagingDirectory)
    mv artifact.txt $(Build.ArtifactStagingDirectory)/
  displayName: 'Create Artifact'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'my-artifact'
    publishLocation: 'Container'

- script: |
    sshpass -p "$(SFTP_PASSWORD)" scp -o StrictHostKeyChecking=no \
      $(Pipeline.Workspace)/my-artifact/artifact.txt sftpuser@$(SFTP_SERVER_IP):uploads/artifact.txt
  displayName: 'Copy to SFTP Server'
  env:
    SFTP_PASSWORD: $(sftp_password)
    SFTP_SERVER_IP: $(sftp_server_ip)
