trigger:
  - main

pool:
  name: "SelfHostedAgents"  # Use the correct pool name

steps:
# Step 1: Checkout the repository
- checkout: self  # Explicit checkout step

# Step 2: Create an artifact
- script: |
    echo "Hello World!" > artifact.txt5
    mkdir -p $(Build.ArtifactStagingDirectory)
    mv artifact.txt5 $(Build.ArtifactStagingDirectory)/
  displayName: 'Create Artifact'

# Step 3: Publish the artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'my-artifact'
    publishLocation: 'Container'

# Step 4: Download the artifact (Ensures it's available on the agent)
- task: DownloadBuildArtifacts@0
  displayName: 'Download Artifact'
  inputs:
    artifactName: 'my-artifact'
    downloadPath: '$(Build.ArtifactStagingDirectory)'

# Step 5: Copy artifact to SFTP server
- script: |
    sshpass -p "$(SFTP_PASSWORD)" scp -o StrictHostKeyChecking=no \
      $(Build.ArtifactStagingDirectory)/artifact.txt5 sftpuser@$(SFTP_SERVER_IP):uploads/artifact.txt5
  displayName: 'Copy to SFTP Server'
  env:
    SFTP_PASSWORD: $(sftp_password)
    SFTP_SERVER_IP: $(sftp_server_ip)



- script: |
    scp /sftp/uploads/artifact.txt5 coditas@52.172.96.181:/home/coditas/
  displayName: 'Copy to Ubuntu Server'

